spring:
  application:
    name: cnhash

  # Connexion à PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/cnhashdb
    username: chijou
    password: duro@chijou
    driver-class-name: org.postgresql.Driver

  # Configuration JPA pour tes tests de collision
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Activation de l'AOP pour tes mesures de performance
  aop:
    proxy-target-class: true

server:
  port: 8081 # Port différent de ton appli clinique pour éviter les conflits

# Configuration personnalisée pour ton moteur cnhash
cnhash:
  algorithm: SHA-256
  version: 1.0.0
